const colors = {
    color_01: '#35A298',
    color_02: '#d1dae8',
    color_03: '#000000',
    color_04: '#8080b4',
    color_05: '#e3e3f7',
    color_06: '#9e9e9e',
    color_07: '#cccccc',
    color_08: '#ffffff',
    color_09: '#676793',
    color_10: '#f9f9f9',
    color_11: '#161633',
    color_12: '#2c4451',
    color_13: '#212147',
    color_14: '#333333',
    color_15: '#383875',
    color_16: '#212147',
};

export default {
    mobile: {},
    desktop: {
        app: {},
        login: {
            borderColor: colors.color_03,
            shadowColor: colors.color_03,
            backgroundLogin: colors.color_15,
            buttonsWrapperColor: colors.color_03,
            settingsBorderBottom: colors.color_07,
            buttonHover: colors.color_15,
            textNotActive: colors.color_08,
            buttonShadow: colors.color_16,
            textForm: colors.color_03,
            buttonActive: colors.color_08,
            textActive: colors.color_14,
        },
        signIn: {
            borderColor: colors.color_03,
            shadowColor: colors.color_03,
            backgroundLogin: colors.color_15,
            buttonsWrapperColor: colors.color_03,
            settingsBorderBottom: colors.color_07,
            buttonHover: colors.color_15,
            textNotActive: colors.color_08,
            buttonShadow: colors.color_16,
            textForm: colors.color_03,
            buttonActive: colors.color_08,
            textActive: colors.color_14,
        },
    },
};